name: build_pr

on:
  pull_request:
    branches: [ master ]
  
jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
    - name: Unit Tests
      uses: actions/checkout@v2
      run: swift test
 
